/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumFieldItemFieldType } from "./EnumFieldItemFieldType";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { SectionToFieldUpdateManyWithoutFieldItemsInput } from "./SectionToFieldUpdateManyWithoutFieldItemsInput";
import { Type } from "class-transformer";
import { EnumFieldItemValidationType } from "./EnumFieldItemValidationType";
@InputType()
class FieldItemUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumFieldItemFieldType,
  })
  @IsEnum(EnumFieldItemFieldType)
  @IsOptional()
  @Field(() => EnumFieldItemFieldType, {
    nullable: true,
  })
  fieldType?: "SingleLineText" | "Number" | "MultiLineText";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fieldValue?: string | null;

  @ApiProperty({
    required: false,
    type: () => SectionToFieldUpdateManyWithoutFieldItemsInput,
  })
  @ValidateNested()
  @Type(() => SectionToFieldUpdateManyWithoutFieldItemsInput)
  @IsOptional()
  @Field(() => SectionToFieldUpdateManyWithoutFieldItemsInput, {
    nullable: true,
  })
  sectionToFields?: SectionToFieldUpdateManyWithoutFieldItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;

  @ApiProperty({
    required: false,
    enum: EnumFieldItemValidationType,
  })
  @IsEnum(EnumFieldItemValidationType)
  @IsOptional()
  @Field(() => EnumFieldItemValidationType, {
    nullable: true,
  })
  validationType?: "Email" | "Web" | "Number" | null;
}
export { FieldItemUpdateInput };
