/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumFieldItemFieldType } from "./EnumFieldItemFieldType";
import { IsEnum, IsString, IsOptional, ValidateNested } from "class-validator";
import { SectionToFieldCreateNestedManyWithoutFieldItemsInput } from "./SectionToFieldCreateNestedManyWithoutFieldItemsInput";
import { Type } from "class-transformer";
import { EnumFieldItemValidationType } from "./EnumFieldItemValidationType";
@InputType()
class FieldItemCreateInput {
  @ApiProperty({
    required: true,
    enum: EnumFieldItemFieldType,
  })
  @IsEnum(EnumFieldItemFieldType)
  @Field(() => EnumFieldItemFieldType)
  fieldType!: "SingleLineText" | "Number" | "MultiLineText";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fieldValue?: string | null;

  @ApiProperty({
    required: false,
    type: () => SectionToFieldCreateNestedManyWithoutFieldItemsInput,
  })
  @ValidateNested()
  @Type(() => SectionToFieldCreateNestedManyWithoutFieldItemsInput)
  @IsOptional()
  @Field(() => SectionToFieldCreateNestedManyWithoutFieldItemsInput, {
    nullable: true,
  })
  sectionToFields?: SectionToFieldCreateNestedManyWithoutFieldItemsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: false,
    enum: EnumFieldItemValidationType,
  })
  @IsEnum(EnumFieldItemValidationType)
  @IsOptional()
  @Field(() => EnumFieldItemValidationType, {
    nullable: true,
  })
  validationType?: "Email" | "Web" | "Number" | null;
}
export { FieldItemCreateInput };
