/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EnumFieldFieldType } from "./EnumFieldFieldType";
import { IsEnum, IsOptional, IsString, ValidateNested } from "class-validator";
import { Field } from "./Field";
import { SectionToFieldUpdateManyWithoutFieldsInput } from "./SectionToFieldUpdateManyWithoutFieldsInput";
import { Type } from "class-transformer";
import { EnumFieldValidationType } from "./EnumFieldValidationType";
@InputType()
class FieldUpdateInput {
  @ApiProperty({
    required: false,
    enum: EnumFieldFieldType,
  })
  @IsEnum(EnumFieldFieldType)
  @IsOptional()
  @Field(() => EnumFieldFieldType, {
    nullable: true,
  })
  fieldType?: "SingleLineText" | "Number" | "MultiLineText";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  fieldValue?: string | null;

  @ApiProperty({
    required: false,
    type: () => SectionToFieldUpdateManyWithoutFieldsInput,
  })
  @ValidateNested()
  @Type(() => SectionToFieldUpdateManyWithoutFieldsInput)
  @IsOptional()
  @Field(() => SectionToFieldUpdateManyWithoutFieldsInput, {
    nullable: true,
  })
  sectionToFields?: SectionToFieldUpdateManyWithoutFieldsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;

  @ApiProperty({
    required: false,
    enum: EnumFieldValidationType,
  })
  @IsEnum(EnumFieldValidationType)
  @IsOptional()
  @Field(() => EnumFieldValidationType, {
    nullable: true,
  })
  validationType?: "Email" | "Web" | "Number" | null;
}
export { FieldUpdateInput };
